server: 
    port: 8088
      
spring:
  mvc: 
      view: 
      prefix: /pages
      suffix: .html
  freemarker:
    suffix: .html
    charset: UTF-8 #编码格式
    cache: false #缓存配置
    content-type: text/html
  datasource:
    url: jdbc:mysql://192.168.10.8:3306/m_?useUnicode=true&characterEncoding=utf8
    username: root
    password: zhsq1234
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    maxActive: 300
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 180000
    logAbandoned: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      maxFileSize: 2Mb
      maxRequestSize: 100Mb