package cn.m.mappers;

import cn.m.models.Customer;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    @Insert({
        "insert into customer (id, cusName, ",
        "mobile, address, ",
        "status, userid)",
        "values (#{id,jdbcType=INTEGER}, #{cusname,jdbcType=VARCHAR}, ",
        "#{mobile,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=CHAR}, #{userid,jdbcType=VARCHAR})"
    })
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    @InsertProvider(type=CustomerSqlProvider.class, method="insertSelective")
    int insertSelective(Customer record);
}