package cn.m.mappers;

import cn.m.models.Order;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated
     */
    @Insert({
        "insert into order_ (id, cusId, ",
        "createtime)",
        "values (#{id,jdbcType=INTEGER}, #{cusid,jdbcType=VARCHAR}, ",
        "#{createtime,jdbcType=TIMESTAMP})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated
     */
    @InsertProvider(type=OrderSqlProvider.class, method="insertSelective")
    int insertSelective(Order record);
}